# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 spatterIight
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Jackett installation tasks
  when: jackett_enabled | bool
  tags:
    - setup-all
    - setup-jackett
    - install-all
    - install-jackett
  block:
    - name: Validate Jackett configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Jackett
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Jackett uninstallation tasks
  when: not jackett_enabled | bool
  tags:
    - setup-all
    - setup-jackett
  block:
    - name: Uninstall Jackett
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
