---

- name: Fail if required Jackett settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - jackett_uid
    - jackett_gid
    - jackett_hostname

- name: Fail if Jackett architecture is not supported
  ansible.builtin.fail:
    msg: >
      Your configuration specifies a CPU architecture (`{{ jackett_arch }}`) which is not currently supported.
      This Jackett role also does not support self-building yet, so it's not possible to make use of it.
  when: "jackett_arch not in ['amd64', 'arm64']"

- name: Validate Jackett Traefik configuration
  when: jackett_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Jackett Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - jackett_container_labels_traefik_hostname
        - jackett_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `jackett_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if jackett_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          jackett_container_labels_traefik_path_prefix (`{{ jackett_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/jackett`).
      when: "jackett_container_labels_traefik_path_prefix != '/' and jackett_container_labels_traefik_path_prefix[-1] == '/'"
